version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/New_York"
    target-branch: "main"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      - dependency-name: "ai"
        versions: ["4.x"]
      - dependency-name: "next"
        versions: ["15.4.x"]
      - dependency-name: "eslint-config-next"
        versions: ["15.4.x"]
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "react-markdown"
          - "react-syntax-highlighter"
          - "use-local-storage-state"
      langchain:
        patterns:
          - "langchain"
          - "@langchain/*"
      types:
        patterns:
          - "@types/*"
      fontawesome:
        patterns:
          - "@fortawesome/*"
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      postcss:
        patterns:
          - "postcss"
          - "postcss-*"
          - "@fullhuman/postcss-purgecss"
          - "autoprefixer"
      conventional-changelog:
        patterns:
          - "conventional-changelog*"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/New_York"
    target-branch: "main"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
